### ISSUE TITLE
Distinguish signedness on operations instead of types

### ISSUE THREAD

**Issue by bjorn3** [ykjit/yk#102]
Have no separate unsigned and signed integer types and for example a separate `udiv` and `sdiv` operation instead of a single `div` operation that works differently depending on the signedness of the input types. At the machine level there are no different unsigned and signed registers. Cranelift also doesn't have different unsigned and signed integer types, so not having it in SIR makes translation easier.

**Comment by vext01** [comment]
Closing, as this is for the old yk design.
