### ISSUE TITLE
Remove usize and isize types

### ISSUE THREAD

**Issue by bjorn3** [ykjit/yk#103]
SIR is target specific anyway as it contains field offsets that differ from target to target, so using usize/isize has no advantages over using u32/u64 depending on the target pointer size.

**Comment by vext01** [comment]
Good point.

But I wonder if there are cases where making a distinction between a u64 and a usize is important?

**Comment by bjorn3** [comment]
I don't think there are any. At least in cg_clif I didn't need to make the distinction anywhere. The difference between usize and u64 (on 64bit systems) is only relevant for source level compatibility with multiple pointer sizes.

**Comment by vext01** [comment]
I was thinking about if they might have different trait impls, but I think you'd just get a call to the correct target anyway.

**Comment by ltratt** [comment]
I am generally a fan of using `usize`/`isize` when we're referencing machine-word-sized things, because it makes the connection clearer. `u32`/`u64`, to me, mean "I want this size irrespective of the machine word size."

**Comment by vext01** [comment]
There's certainly "intent" attached to usize/isize. The question is, do we care at runtime/codegen?

**Comment by ltratt** [comment]
It's not a die-in-a-ditch thing for me, so long as we're consistent using one scheme in the codebase.

**Comment by bjorn3** [comment]
Cranelift doesn't have a `usize` type, so if `Load` and `Store` were to require an `usize` as address argument, I would have to translate the `i64` clif type on 64bit and `i32` on 32bit targets to `usize`, which is even more confusing with regard to intent.

**Comment by vext01** [comment]
Closing, as this is for the old yk design.
