### ISSUE TITLE
Missing things to jit yklua

### ISSUE THREAD

**Issue by ptersilie** [ykjit/yk#1157]
Here's a list of missing AOT lowerings, trace builder handling, and codegen that are required to run yklua. This list is not complete, but the most I could get out of yklua before other errors were getting in the way of looking further down the trace:

- [x] tracebuilder: Sub (Lukas)
- [x] tracebuilder: AShr (Lukas)
- [x] tracebuilder: Mul (Lukas)
- [x] tracebuilder: Xor (Lukas)
- [ ] tracebuilder: SRem (Lukas)
- [x] AOT lowering: ptrtoint (Lukas)
- [x] AOT lowering: ashr exact (Lukas)
- [x] Unimplemented("  %4032 = icmp eq ptr %4030, null, !dbg !10987") (Edd)

Only the first two (`Sub` and `AShr`) are needed to reach the codegen for the first trace in db.lua.

If you take one of these on, please edit this comment and add your name, so others know it's being worked on. Good luck!

**Comment by vext01** [comment]
Me and Lukas were discussing yesterday whether `sub` should be canonicalised to `add` at some point in the pipeline (maybe tracebuilder?).

E.g. `sub x, 1` => `add x, -1`.

**Comment by vext01** [comment]
Not also that there is already (naive) codegen for `Mul` since we needed it for dynamic ptradd.

**Comment by vext01** [comment]
I guess ptrtoint is a no-op, but the type changes?

**Comment by ltratt** [comment]
> Me and Lukas were discussing yesterday whether sub should be canonicalised to add at some point in the pipeline (maybe tracebuilder?).

We will want to think about canonicalisation at some point, but not right now IMHO.

**Comment by vext01** [comment]
> We will want to think about canonicalisation at some point, but not right now IMHO.

Well it's easier to canonicalise in this way right off the bat, since you can re-use the existing `cg_add` rather than writing a new `cg_sub`.

**Comment by ltratt** [comment]
> Well it's easier to canonicalise in this way right off the bat

Yes, but `cg_add` and `cg_sub` are so simple right now that I'd rather have the near-duplicated code than distract ourselves with premature canonicalisation. That is something that will require some real research of other systems, which will take much more time than the (currently minor) code duplication.

**Comment by vext01** [comment]
As you wish. Just an idea.

**Comment by ltratt** [comment]
I think this is now complete (or close to) and am closing it, but feel free to reopen if I'm wrong to do so.
