### ISSUE TITLE
AOT IR may fail to print due to unimplemented instructions.

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#1173]
If you have LLVM IR like:
```
%1 = blah %args...
%2 = add %1, ...
```

and `blah` isn't implemented, then printing the AOT IR will fail, as at some point the type of the value made by the first instruction is queried, and in our IR, an unimplemented instruction makes no value.

I wonder if we should have unimplemented instructions generate an "undefined" value of the type the instruction would have otherwise created?

**Comment by ltratt** [comment]
I think this problem will naturally sort itself out as we flesh things out more. I'm closing but we can reopen if we really want to.
