### ISSUE TITLE
Split `PtrAdd` into two instructions?

### ISSUE THREAD

**Issue by ltratt** [ykjit/yk#1201]
While investigating why `jit_ir::IntegerTy::make_constant` does weird things (more on that in a bit), I traced back into `trace_builder` which handles `aot_ir::PtrAdd`. A quick reminder of the relevant part of its definition:

```rust
PtrAdd {
    ...
    /// The constant offset (in bytes).
    ///
    /// This is signed to allow for negative array indices and negative pointer arithmetic.
    const_off: isize,
    ...
```

In trace_builder when we encounter `PtrAdd` we do this:

```
let co_ty = jit_ir::IntegerTy::new(32);
let co_const = co_ty.make_constant(&mut self.jit_mod, const_off)?;
```

Now the "obvious" problem is that `make_constant` silently truncates the `isize` to an `i32`, but the less obvious problem is that it seems to me that trace_builder is fundamentally incorrect in assuming the offset is 32 bits full stop. Here's the [relevant part of LLVM's definition of `getelementptr`](https://llvm.org/docs/LangRef.html#id236):

>When indexing into a (optionally packed) structure, only i32 integer constants are allowed (when using a vector of indices they must all be the same i32 integer constant). When indexing into an array, pointer or vector, integers of any width are allowed, and they are not required to be constant.

So the "constant" offset, if it exists, can be less than -- or more than! -- 32 bits. For a struct, it's hard to imagine that 32 bits isn't enough to represent the size of the struct. For an array, though, one could definitely imagine a constant offset bigger than 32 bits. I think `PtrAdd` is intended to be a simplification of getelementptr, but it looks to me like it's currently a sort of 1:1 mapping from getelementptr, except `PtrAdd` doesn't get some of that mapping correct.

Although I'm not 100% sure I think the fix here is multistage:

1. Why don't we split `getelementptr` into more than one instruction? For example we might have `StructPtrAdd` which takes a constant `i32` and `ArrayPtrAdd` which can take constants-or-not any-integer-types.
2. `StructPtrAdd` allows us to assert in ykllvm that we *really* have an offset which fits in an `i32`. `StructPtrAdd`'s `const_off` then becomes `i32`.
3. trace_builder will no longer have to worry about silently (incorrectly!) truncate an `isize` to an `i32` when translating `StructPtrAdd`.

One probable advantage of this is that `StructPtrAdd` becomes a very simple instruction whose semantics we can easily understand: `ArrayPtrAdd` will end up with most of the more complex stuff, but at least we've stripped out *some* of the complexity by offloading it to `StructPtrAdd`.

**Comment by vext01** [comment]
> jit_ir::IntegerTy::new(32);

That may well be wrong. I think the upper limit of a GEP index is the width of the pointer indexing type of the address space in question.

> Why don't we split getelementptr into more than one instruction? For example we might have StructPtrAdd which takes a constant i32 and ArrayPtrAdd which can take constants-or-not any-integer-types.

I'm not certain it's easy to pick them apart.

Our `PtrAdd` implementation piggy backs off of [GetElementPtrInst::collectOffset()](https://llvm.org/doxygen/classllvm_1_1GetElementPtrInst.html#a600fb2213a893d3db4d03ea9fe6b9e63), which smooshes down as many constant aggregate accesses into one pointer bump as possible (regardless of type). After the static pointer bump has been computed, only dynamic element accesses for vectors/arrays are left.

I did it like this because I trust LLVM more to get it right than I do myself. The semantics are quite complicated.

**Comment by ltratt** [comment]
@vext01 AFAICS what we're doing right now is wrong, so we're probably not going to make the situation worse ;) What I'm suggesting is splitting out two cases: one with a *definitely constant* offset (if we do the struct case, this ends up being a *definitely constant unsigned* constant, which is even easier); and then "everything else". At the moment our `PtrAdd` must, by definition, be as complex as getelementptr (modulo anything we don't support), so splitting out one case doesn't seem difficult to me?

**Comment by vext01** [comment]
As long as you don't mind the constant pointer bump opcode handling both constant array/vector accesses *and* struct field accesses it isn't too difficult.

If you want to tease those apart, it will be more work.

**Comment by ltratt** [comment]
For reference, https://github.com/ykjit/yk/pull/1202 is related to this, in that it deals with other places where we've got potential integer type confusion (and thus the possibility of extension/truncation) resulting from AOT IR and trace building.

**Comment by vext01** [comment]
We can, but it means we can't use `collectOffset()` to do the heavy lifting any more, and that's a non-trivial routine that I'd rather LLVM handles for us.

Let me give an example:
```
my_struct.some_array[4].some_field;
```

Will be flattened into one constant offset, since there's nothing dynamic about it. Struct field accesses are always static, and the array index is constant.

So when you use collectOffset():
```
bool GetElementPtrInst::collectOffset(
    const DataLayout &DL, unsigned BitWidth,
    MapVector<Value *, APInt> &VariableOffsets,
    APInt &ConstantOffset) const;
```

For the above example, `ConstantOffset` would contain the static offset, and `VariableOffsets` would be empty. `ConstantOffset` smooshes the differently-typed (struct and array here) accesses into one pointer bump, and there's no way (using this function) to separate them.

I don't reccommend trying to split the different access type apart, because it's not going to be easy.

I'd be OK with separating out GEPs into a static opcode and a dynamic opcode, because that's much easier and less error prone.

**Comment by vext01** [comment]
Put differently:

> Or, at least, split out something like ConstPtrAdd from DynamicPtrAdd or similar? 

Yes, but `ConstPtrAdd` would handle all constant accesses for any aggregate access. I'm OK with that.

**Comment by ltratt** [comment]
>I'd be OK with separating out GEPs into a static opcode and a dynamic opcode, because that's much easier and less error prone.

I think this is really what we care about *but* note that, AFAICS, struct types are always `i32` offsets but array offsets can be (multiple?) arbitrary integer types?

Another way of looking at this is that `getelementptr` can do all sorts of weird things, but we probably only commonly see a subset of cases:

1. Add a single constant offset. Struct types are always `PtrAddI32` but we may also see `PtrAddI8` (and friends) for array accesses?
2. All the other complex stuff that `getelementptr` can do: weird integer types, dynamic values, and god knows what.

The advantage of (1) is that if we have (say) `PtrAddI32` we know the constant has been checked by ykllvm to be exactly 32-bits wide, and trace_builder doesn't have to do any checking. [Similarly for `PtrAddI8` etc.] But for anything in case (2), trace_builder might have to do a lot of checking / careful handling.

**Comment by vext01** [comment]
> AFAICS, struct types are always i32 offsets but array offsets can be (multiple?) arbitrary integer types?

That's true, but to simplify things we extend them up to the pointer indexing size so that they can be treated uniformly:
https://github.com/ykjit/ykllvm/blob/90737baafa1f5f7aecd046258ff77f708ec0529c/llvm/lib/YkIR/YkIRWriter.cpp#L851

**Comment by ltratt** [comment]
>That's true, but to simplify things we extend them up to the pointer indexing size so that they can be treated uniformly:

Yes, and that's what causes the problems I've noted in this issue and in #1202: we end up having to truncate things at run-time in trace_builder.

That said, now that #1202 at least borks at run-time if we get things wrong, this issue is a little less pressing. I still think we should think about shoving more of this stuff off to AOT compile-time in ykllvm, but we don't have to do it right now.

**Comment by vext01** [comment]
Just to support that, all GEPs indices are internally extended up to the size of a (signed) pointer index type, so the fact that struct indices are i32 isn't all that important. It's just an implementation detail of the LLVM bitcode language:

> The indices are first converted to offsets in the pointer’s index type. If the currently indexed type is a struct type, the struct offset corresponding to the index is sign-extended or truncated to the pointer index type. Otherwise, the index itself is sign-extended or truncated, and then multiplied by the type allocation size (that is, the size rounded up to the ABI alignment) of the currently indexed type. The offsets are then added to the low bits of the base address up to the index type width, with silently-wrapping two’s complement arithmetic

https://llvm.org/docs/LangRef.html#id237

**Comment by vext01** [comment]
We raced.

But I don't think #1202 is related to this. I just chose to encode switch indices as u64 because we need a type "big enough" for most common case values (until we have arbitrary precision int support).

**Comment by ltratt** [comment]
This was fixed in https://github.com/ykjit/yk/pull/1213.
