### ISSUE TITLE
Make SWT run with the new codegen.

### ISSUE THREAD

**Issue by ptersilie** [ykjit/yk#1290]
In order to get side-tracing (https://github.com/ykjit/yk/pull/1287) working I had to break code that `jitc_ykllvm` depends on, so I had to disable `jitc_ykllvm`. This in turn broke SWT, which I then also had to disable: https://github.com/ykjit/yk/pull/1287/commits/8d4c522e209e8b4a0777e822344c3b930224fb2a.

In order to get SWT working again we need to adapt it to use the new codegen.

**Comment by vext01** [comment]
I believe this was solved (quickly) in https://github.com/ykjit/yk/pull/1322

Please re-open if not.
