### ISSUE TITLE
Calls assume the SysV ABI

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#132]
When in fact we probably want to choose either the Rust ABI or the SysV ABI depending upon if the callee is foreign or not.

**Comment by bjorn3** [comment]
I am pretty sure you are actually assuming something closer to the Rust ABI than the SysV ABI. The SysV ABI for example packs `struct A(u32, u16);` into a single register when passed.

**Comment by vext01** [comment]
We are probably implementing a frakenABI then :P

**Comment by bjorn3** [comment]
Even cg_clif doesn't follow the SysV ABI. It only recently got support for building proc-macros that are compatible with a cg_llvm built rustc.

**Comment by vext01** [comment]
Hrm. How do you call foreign functions without proper SysV?

**Comment by bjorn3** [comment]
It implements enough to support scalars and some struct arguments (those that need to be passed in one register per field and don't have `#[repr(C)]`, or need to be passed on the stack). This is enough for most calls. The objc and capstone crates don't work though.

**Comment by vext01** [comment]
I see.

We've not got as far as passing structs to calls or anything, so that's why we've got away with it so far.

I only learned the other day that things like fat pointers are returned using `rax:rdi` in the Rust ABI and hence this issue.

**Comment by vext01** [comment]
Closing, as this is for the old yk design.
