### ISSUE TITLE
What do all the things in yksmp mean?

### ISSUE THREAD

**Issue by ltratt** [ykjit/yk#1334]
yksmp has very few docstring, which meant that when I look at e.g. [Location](https://github.com/ykjit/yk/blob/master/yksmp/src/lib.rs#L36) I am left confused:

```rust
pub enum Location {
    Register(u16, u16, i32, u16),
    Direct(u16, i32, u16),
    Indirect(u16, i32, u16),
    Constant(u32),
    LargeConstant(u64),
}
```

Some of these are somewhat obvious (`Constant`) but can we at least briefly document these sorts of things? If nothing else, maybe we can link to the relevant part(s) of the LLVM spec?

**Comment by ltratt** [comment]
So here's something that's really surprised me: `Loaction::Direct` can return both positive and negative stack offsets! I assumed the `i32` was always `>= 0` but a quick test run on yk's lang_tests shows values such as [-56, 0, 4]. I'm not quite sure how to interpret this: does a positive value mean that we reach into a parent function frame? If so, how does that interact with trace frames?

**Comment by vext01** [comment]
The document you are looking for is:
https://llvm.org/docs/StackMaps.html#stack-map-format

![image](https://github.com/user-attachments/assets/0074a5a0-53a6-45dd-a64b-47e1459365ef)

> does a positive value mean that we reach into a parent function frame?

It depends what register the offset is relative to.

Notice how a direct record is a `Reg + Offset` pair.

> Loaction::Direct can return both positive and negative stack offsets!

An example, the same stack location can be addressed (on x64) as a positive offset from the stack pointer, or a negative index from the base pointer.

The register involved may not even be a stack-related register. It could be any old register (e.g. `rax`) holding any old address that (after the offset is applied) points into the stack somewhere.

**Comment by ltratt** [comment]
Fixed in https://github.com/ykjit/yk/pull/1355.
