### ISSUE TITLE
What are the implications of #1318 (removing the trace input struct)?

### ISSUE THREAD

**Issue by ltratt** [ykjit/yk#1338]
I've been digging into the x64 codegen and register allocator and I will admit that I have tied myself in knots trying to understand how #1318 has changed the system. That doesn't mean that #1318 isn't fully correct -- I may just not yet understand what it's doing properly! There seem to be 3 things that I can't adequately explain to myself.

First is that I don't understand why we sometimes calculate addresses and not values (in the [current code](https://github.com/ykjit/yk/blob/master/ykrt/src/compile/jitc_yk/codegen/x64/mod.rs#L812) or [the original PR](https://github.com/ykjit/yk/pull/1318/files#diff-150b793f9518b19505892d1496e8641dc1de27061360bfb755cb1c85159f3eaeR778)):

```rust
match self.m.type_(inst.tyidx()) {
  Ty::Integer(_) | Ty::Ptr => {
    let [tgt_reg] = self.ra.get_gp_regs_avoiding(
      &mut self.asm,
      iidx,
      [RegConstraint::Output],
      RegSet::from_vec(&STACKMAP_GP_REGS),
    );
    ...
    match m {
      VarLocation::Direct { frame_off, size } => {
        // FIXME If we prime the register allocator with the interpreter frames
        // stack size and don't create a new frame in the trace epilogue we can
        // reference values directly using the current RBP value.
        match size {
            8 => dynasm!(self.asm
                 ; mov Rq(tgt_reg.code()), QWORD [Rq(Rq::RBP.code())]
                 ; lea Rq(tgt_reg.code()), [Rq(tgt_reg.code()) + frame_off]
            ),
            _ => panic!(),
        }
```

The `lea` towards the bottom of that code sample really surprises me: if we've got an object of `Ty::Integer` (for example), how is it correct to end up with an address to the stack? I would expect code more along the lines of:

```rust
match size {
  8 => dynasm!(self.asm
  ; mov Rq(tgt_reg.code()), QWORD [Rq(Rq::RBP.code())]
  ; mov Rq(tgt_reg.code()), [Rq(tgt_reg.code())]
  ),
```

i.e. loading the value out of the stack.

The second thing is that `VarLocation` has (amongst others) now has these three variants:

```rust
pub(crate) enum VarLocation {
    /// The SSA variable is on the stack.
    Stack {
        /// The offset from the base of the trace's function frame.
        frame_off: u32,
        /// Size in bytes of the allocation.
        size: usize,
    },
    /// The SSA variable is a stack pointer with the value `RBP-frame_off`.
    Direct {
        /// The offset from the base of the trace's function frame.
        frame_off: i32,
        /// Size in bytes of the allocation.
        size: usize,
    },
    /// The SSA variable is behind a pointer that's stored on the stack: `[RBP-frame_off]`.
    Indirect {
        /// The offset from the base of the trace's function frame.
        frame_off: i32,
        /// Size in bytes of the allocation.
        size: usize,
    },
   ...
}
```

What's surprising to me is: why are `Stack` and `Direct` different? I don't know what "The SSA variable is a stack pointer" is supposed to mean: in a sense this is my `lea` query rephrased. I actually misread this as "The SSA variable is on the stack" i.e. I thought `Stack` and `Direct` were supposed to be the same, with the only difference being `frame_off`s `i32`/`u32`. Is there a reason that `Direct` returns addresses and not values?

[Update: based on @vext01's comment https://github.com/ykjit/yk/issues/1334#issuecomment-2268496639 I wonder if `Direct` has to store which register it's relative to?]

The final thing relates to the `i32`/`u32` offsets. Notice this comment for `Direct`:

```rust
/// The SSA variable is a stack pointer with the value `RBP-frame_off`.
Direct { ... }
```

*but* when you look at the code that uses `frame_off` you will notice:

```
; lea Rq(tgt_reg.code()), [Rq(tgt_reg.code()) + frame_off]
```

i.e. we calculate `+` (not `-`!). Maybe this is just a documentation typo, but I think something deeper is going on. If I look at the values we can get for `Direct::frame_off` they can be negative, zero, or positive. For example on one test I saw values of {-56, 0, 4} for `Direct::frame_off`. In the `Stack` variant we have a `u32` and we always calculate `Rbp-frame_off`: what does it mean for `Direct::frame_off` if we sometimes have positive or negative values? Are we somehow calculating things in a parent frame or ... ?

**Comment by vext01** [comment]
I'm not fully qualified to answer this, but from what I can remember from discussions with lukas:

 - **before**: trace inputs loaded from a +ve offset from a pointer to the trace inputs struct.
 - **after**: trace inputs loaded from a -ve offset from the base pointer, i.e. reaching into the parent frame.

Could it be to do with that?

**Comment by ltratt** [comment]
Notice that I can see `Direct` including positive and negative values! Does that mean that we have to generate code differently for the positive / negative cases?

**Comment by vext01** [comment]
I don't think so. You should be able to simply add the offset, because if you add a negative value, you will get a negative offset and all should be well.

**Comment by ltratt** [comment]
Here's another surprising output of #1318: we can get distinct SSA values referencing the same register. [Perhaps this has always been the case and #1318 just shows us this explicitly]. Consider `simplecall.c` whose core is:

```c
int main(int argc, char **argv) {
  YkMT *mt = yk_mt_new(NULL);
  yk_mt_hot_threshold_set(mt, 0);
  YkLocation loc = yk_location_new();

  int res = 9998;
  int i = 4;
  NOOPT_VAL(loc);
  NOOPT_VAL(res);
  NOOPT_VAL(i);
  while (i > 0) {
    yk_mt_control_point(mt, &loc);
    fprintf(stderr, "%d\n", i);
    foo(i);
    res += 2;
    i--;
  }
...
```

The resulting trace starts with:

```
   |entry:
   |    %0: ptr = load_ti Register(3, 8, 0, 0)
   |    %1: ptr = load_ti Direct(6, -40, 8)
   |    %2: ptr = load_ti Direct(6, -32, 8)
   |    %3: ptr = load_ti Register(3, 8, 0, 0)
   |    %4: ptr = load_ti Register(15, 8, 0, 0)
   |    %5: ptr = load_ti Register(5, 8, 0, 15)
```

notice that both `%0` and `%3` reference register 3. That suggests to me there's some sort of aliasing going on, but I don't see anything plausible in the C code. I'm less confident that I can read the AOT output correctly:

```
   |func main(%arg0: i32, %arg1: ptr) -> i32 {
   |  bb0:
   |    %0_0: i32 = arg(0)
   |    %0_1: ptr = arg(1)
   |    %0_2: ptr = call malloc(1000000i64)
   |    *@shadowstack_0 = %0_2
   |    %0_4: ptr = alloca ptr, 1, 8
   |    %0_5: ptr = alloca {0: i64}, 1, 8
   |    %0_6: ptr = ptr_add %0_2, 0
   |    %0_7: ptr = ptr_add %0_2, 4
   |    br bb1
   |  bb1:
   |    # simplecall.c:52: YkMT *mt = yk_mt_new(NULL);
   |    %1_0: ptr = call yk_mt_new(0x0)
   |    br bb2
   |  bb2:
   |    *%0_4 = %1_0
   |    # simplecall.c:53: yk_mt_hot_threshold_set(mt, 0);
   |    call yk_mt_hot_threshold_set(%1_0, 0i32)
   |    # simplecall.c:54: YkLocation loc = yk_location_new();
   |    br bb3
   |  bb3:
   |    %3_0: i64 = call yk_location_new()
   |    br bb4
   |  bb4:
   |    *%0_5 = %3_0
   |    # simplecall.c:56: int res = 9998;
   |    *%0_6 = 9998i32
   |    # simplecall.c:57: int i = 4;
   |    *%0_7 = 4i32
   |    # simplecall.c:59: NOOPT_VAL(res);
   |    br bb5
   |  bb5:
   |    %5_0: i32 = load %0_6
   |    # simplecall.c:60: NOOPT_VAL(i);
   |    br bb6
   |  bb6:
   |    %6_0: i32 = load %0_7
   |    # simplecall.c:61: while (i > 0) {
   |    br bb7
   |  bb7:
   |    br bb8
   |  bb8:
   |    %8_0: i32 = load %0_7
   |    %8_1: i1 = sgt %8_0, 0i32
   |    condbr %8_1, bb9, bb13 [safepoint: 1i64, (%0_2, %0_4, %0_5, %0_6, %0_7, %8_1)]
   |  bb9:
   |    # simplecall.c:62: yk_mt_control_point(mt, &loc);
   |    %9_0: ptr = load %0_4
   |    call __ykrt_control_point(%9_0, %0_5, 3i64) [safepoint: 3i64, (%0_2, %0_4, %0_5, %0_6, %0_7, %9_0)]
   |    # simplecall.c:63: fprintf(stderr, "%d\n", i);
   |    br bb10
```

but there is one possible candidate there:

```
   |    %0_2: ptr = call malloc(1000000i64)
...
   |    %0_6: ptr = ptr_add %0_2, 0
```

Why do we have `ptr_add %0_2, 0`? I guess that's just an unoptimised LLVM thing?

**Comment by vext01** [comment]
> Why do we have ptr_add %0_2, 0? I guess that's just an unoptimised LLVM thing?

Likely yes. Probably a field access to the first field of a struct.

**Comment by ltratt** [comment]
>First is that I don't understand why we sometimes calculate addresses and not values (in the [current code](https://github.com/ykjit/yk/blob/master/ykrt/src/compile/jitc_yk/codegen/x64/mod.rs#L812) or [the original PR](https://github.com/ykjit/yk/pull/1318/files#diff-150b793f9518b19505892d1496e8641dc1de27061360bfb755cb1c85159f3eaeR778)):
>
```rust
match self.m.type_(inst.tyidx()) {
  Ty::Integer(_) | Ty::Ptr => {
    let [tgt_reg] = self.ra.get_gp_regs_avoiding(
      &mut self.asm,
      iidx,
      [RegConstraint::Output],
      RegSet::from_vec(&STACKMAP_GP_REGS),
    );
    ...
    match m {
      VarLocation::Direct { frame_off, size } => {
        // FIXME If we prime the register allocator with the interpreter frames
        // stack size and don't create a new frame in the trace epilogue we can
        // reference values directly using the current RBP value.
        match size {
            8 => dynasm!(self.asm
                 ; mov Rq(tgt_reg.code()), QWORD [Rq(Rq::RBP.code())]
                 ; lea Rq(tgt_reg.code()), [Rq(tgt_reg.code()) + frame_off]
            ),
            _ => panic!(),
        }
```
>
>The lea towards the bottom of that code sample really surprises me: if we've got an object of Ty::Integer (for example), how is it correct to end up with an address to the stack? I would expect code more along the lines of:

I *might* now understand this. I *think* that you can only get `VarLocation::Direct` if `self.m.type_(inst.tyidx()) == Ty::Ptr`. In other words, I think the `Ty::Integer` and `Ty::Ptr` branches probably need splitting. Note that I don't think *all* `Ty::Ptr`s are `VarLocation::Direct`s but I think *no* `Ty::Integer`s are `VarLocation::Direct`s.

**Comment by ltratt** [comment]
I've now got quite a bit further. I sort-of understand `Direct` and `Indirect` and can implement enough of the hacks in the register allocator to make use of them. See https://github.com/ykjit/yk/commit/f4a80cca2117fc5a55ac6e9ce5891dac54b6e017. In non-release mode, this often borks with register aliasing issues (see https://github.com/ykjit/yk/issues/1338#issuecomment-2268814823). *However* note that this makes big_loop.lua 20% slower! I suspect (but in release mode I can't check, as you can't get jit-asm output there) this is because we've now moved shadow stack costs into the core loop of the compiled trace (i.e. we've now replaced one load of `[rpb-off]` to a load of `[rbp]` plus a load of `[rbp-off]`).

Presumably if we can alter ykllvm to only use the shadow stack when strictly necessary most of these costs would go away?

[ would also avoid more of these costs if we did reverse register allocation and/or cached the value of `[rbp]` in a register. But perhaps it's not worth doing either if "don't use the shadow stack as much" solves the bigger problem.]

**Comment by ltratt** [comment]
> suspect (but in release mode I can't check, as you can't get jit-asm output there) this is because we've now moved shadow stack costs into the core loop of the compiled trace (i.e. we've now replaced one load of [rpb-off] to a load of [rbp] plus a load of [rbp-off]).

This is now confirmed. Here's a representative chunk from master:

```
; %301: i32 = load %8
00007f5800eca70e 0000170e: mov r15, [rbp-0x18]
00007f5800eca715 00001715: mov r15d, [r15]
; %302: i32 = and %301, 127i32
00007f5800eca71a 0000171a: mov r14d, 0x7F
00007f5800eca720 00001720: and r15d, r14d
```

and with f4a80cc:

```
; %301: i32 = load %8
00007f3f3afb900b 0000000b: mov r15, [rbp]
00007f3f3afb900f 0000000f: mov r15, [r15-0x48]
00007f3f3afb9017 00000017: mov r15d, [r15]
; %302: i32 = and %301, 127i32
00007f3f3afb901c 0000001c: mov r13d, 0x7F
00007f3f3afb9022 00000022: and r15d, r13d
```

Notice the extra load (`mov r15, [rbp]`).

**Comment by ptersilie** [comment]
I think you've answered most of the questions already. But here's some extra context regarding loading parent frame values. At the moment, the executed trace still has it's own stack. To work around this I've hacked `LoadTraceInputs` to load values from the parent frame and then immediately store the in the JIT frame. However, in order to do so I need access to the `RBP` of the parent frame, which I thus store at the very bottom of the JIT frame. Hence the `mov reg, [rbp]; mov reg, reg + off` dance in `c_loadtraceinput`.

Now when Laurie taught the register allocator to work with the trace inputs directly, we essentially moved that dance into the trace loop, hence the slowdown.

One way to get rid of this, is to move less stuff onto the shadow stack. But the problem will still affect some values that need to be there. The other solution (and I had this on my list as the next work load) is to execute the trace on the frame as the parent. Then we don't need the extra rbp load anymore.

**Comment by ltratt** [comment]
> One way to get rid of this, is to move less stuff onto the shadow stack. But the problem will still affect some values that need to be there. The other (and in my opinion better) solution (and I had this on my list as the next work load) is to execute the trace on the frame as the parent. Then we don't need the extra rbp load anymore.

Agreed on both points. In terms of prioritisation, I think the shadow stack optimisation will have a bigger effect, and is probably easier to do, so I'd be inclined to do it first.

**Comment by ltratt** [comment]
I think we've now more-or-less addressed (or are in the process of addressing) everything in here, so it's time to close this.
