### ISSUE TITLE
create_guard() constant panic

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#1340]
As evidenced [here](https://github.com/ykjit/yk-benchmarks/pull/3#issuecomment-2268572970) we can sometimes hit this panic:

https://github.com/ykjit/yk/blob/ef19fce841dcf695764bfdd25993e7a5f2ad39dd/ykrt/src/compile/jitc_yk/trace_builder.rs#L544).

I recall speaking to @ptersilie about this briefly and he asked me to find the corresponding AOT IR, which I haven't looked at yet.

**Comment by vext01** [comment]
I've finally gotten around to investigating this.

For context, this crash is cropping up when running benchmarks from awfy. Here's one such crash in CI in the wild:
https://github.com/ykjit/yk-benchmarks/pull/3#issuecomment-2273003434

```
0:10:58 Executing run:Havlak (YkLua, awfy, 1500) default None None None
10:10:58     cmd: /ci/yklua/src/yklua  harness.lua Havlak 1  1500
10:10:58     cwd: /ci/awfy/Lua
10:10:58     Run failed. Return code: 139
10:10:58     Output:
10:10:58 
10:10:58         Starting Havlak benchmark ...
10:10:58         thread '<unnamed>' panicked at ykrt/src/compile/jitc_yk/trace_builder.rs:544:25:
10:10:58         explicit panic
10:10:58         note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
10:10:58         Segmentation fault (core dumped)
10:10:58         
10:10:58     Execution has failed, benchmark is aborted.
10:10:58         The benchmark failed 1 times in a row.
```

The code in question is:
https://github.com/ykjit/yk/blob/9dc7866dfff7b84ab28b4020b96c95272d8a3d96/ykrt/src/compile/jitc_yk/trace_builder.rs#L541-L545

The comment seems to be incorrect. A safepoint live variable can reference a constant. Here's what happened for the above crash.

AOR IR:
```
  bb2:
    %2_0: i1 = phi bb0 -> 1i1, bb1 -> %1_1
    condbr %2_0, bb5, bb3 [safepoint: 1536i64, (%0_3, %0_4, %0_5, %0_6, %0_7, %2_0)]
```

We traced the phi node with `bb0` as the predecessor, so the safe point live variable `%2_0` references the constant `1i1` thus triggering the "this cannot happen" panic.

I'm going to attempt a fix. It looks like `GuardInfo` needs to be extended to handle constants.

**Comment by ltratt** [comment]
An alternative solution is to stop trace_builder trying to deal with constants which, AIUI, it currently does. In essence it tries to sort-of optimise constants, when that could be left to later optimisation stages.

**Comment by vext01** [comment]
Fixed by https://github.com/ykjit/yk/pull/1369
