### ISSUE TITLE
Items marked `#[do_not_trace]` still get SIR statements encoded.

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#156]
We should never need the SIR statements for such functions.

It may be useful to keep *some* info around about them though, like the flags.

Perhaps we should split `Body` into two smaller structs and the one containing the SIR statements is wrapped in an `Option`.

**Comment by bjorn3** [comment]
You could also simply not add any SIR statements to the `Body` in ykrustc.

**Comment by vext01** [comment]
Yeah, I considered that too, but thought it'd be nice to have an explicit "it's not here" marker like `None` :)

**Comment by vext01** [comment]
Related: #244.

**Comment by vext01** [comment]
Closing, as this is for the old yk design.
