### ISSUE TITLE
yk and valgrind

### ISSUE THREAD

**Issue by ltratt** [ykjit/yk#177]
On master if we run test on valgrind, it fails:

```
$ valgrind --trace-children=yes cargo dumb
...
running 1 test
thread 'mt::tests::dumb_interpreter' panicked at 'assertion failed: `(left == right)`
  left: `8`,
 right: `10`', ykrt/src/mt.rs:615:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test mt::tests::dumb_interpreter ... FAILED

failures:

failures:
    mt::tests::dumb_interpreter

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 5 filtered out; finished in 6.14s
```

If we look at the step function for that interpreter:

```rust
fn dumb_interp_step(tio: &mut IO) {
    match tio.prog[tio.pc] {
        NOP => {
            tio.pc += 1;
            tio.count += 1;
        }
        RESTART => tio.pc = 0,
        _ => unreachable!(),
    }
}
```

and put a `println("woo");` in at the beginning of the function, then we would expect it to fail when run normally:

```
...
woo
:thread '<unnamed>' panicked at 'not yet implemented: unimplemented constant: const mt::tests::dumb_interpreter::dumb_interp_step::promoted[1]', /home/ltratt/yk/ykcompile/src/lib.rs:437:18
```

However under valgrind:

```
...
woo
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `8`,
 right: `10`', ykrt/src/mt.rs:616:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
FAILED
```

In other words, we're not actually executing any meaningful amount of a trace. Indeed, I *suspect* we're executing the equivalent of:

```rust
fn compiled_trace(inputs: ...) {
}
```

i.e. an empty body. Working guesses:

1. valgrind turns PT off (or something like that).
2. when run under valgrind PT records parts of valgrind which confuse our trace head/tail chopper, which silently return some sort of empty list or similar.

Warning: I could be *very* wrong about this!

I think it's worth having a quick look at this, as it would be good if we can use valgrind for debugging, particularly given how much `unsafe` code we have, but if we can't, we should at least know why not.

**Comment by bjorn3** [comment]
What I think is that PT keeps running but as valgrind does dynamic rewriting of the input code, the rewritten code is recorded as being executed instead of the original code, which results in no matching labels.

**Comment by ltratt** [comment]
We dug a bit further into this and found that we don't get any data out from PT (perhaps because valgrind prevents us turning PT on, or turns it off, or .who knows what). I *think* Edd had a patch which detects the subsequently empty SIR traces, but I can't seem to find it now.

**Comment by vext01** [comment]
Bjorn's idea makes sense. If we execute code that wasn't statically
emitted, it won't have SIR dwarf labels, and thus it won't be possible to
map the blocks.

I was in the mapper earlier, and it (by necessity) ignores PT blocks that
contain no SIR labels. So there's the likely source of your empty trace.

I didn't know that valgrind did dynamic rewriting.

**Comment by ltratt** [comment]
I think the easiest thing, for now, is just to bork if we get a totally empty trace (which, I think, you had a patch for?).

**Comment by ltratt** [comment]
We can probably make use of that. In an ideal world, we'd dynamically shift to software tracing in the presence of valgrind, but that's not something we can do quite yet.

**Comment by vext01** [comment]
> I think the easiest thing, for now, is just to bork if we get a totally empty trace.

That's easily doable.

**Comment by ltratt** [comment]
@bjorn3 also makes a good point about `RUNNING_ON_VALGRIND`. It's possible that we should detect that and say "sorry, we can't run on valgrind at the moment". When the software tracer is ready, we can use that under valgrind automatically?

**Comment by ltratt** [comment]
The good news is that valgrind now seems to unset the "PT supported" CPU flag, so `pt_supported` in hwtrace:

```rust
    fn pt_supported() -> bool {
        let res = unsafe { __cpuid_count(0x7, 0x0) };
        (res.ebx & (1 << 25)) != 0
    }
```

returns false. Tests fail, but they do so in a way that makes a lot more sense than a couple of years ago.

The bad news is that we currently don't have a nice way of telling the user "PT isn't supported, so don't try running this". That's a slightly separate issue, so I'll close this one.
