### ISSUE TITLE
Are our #[bench] benchmarks useful?

### ISSUE THREAD

**Issue by ltratt** [ykjit/yk#197]
We have some `#[bench]` benchmarks but we can't meaningfully compile them:

```
$ RUSTFLAGS="-C tracer=hw" cargo bench
...
error: optimisation cannot be enabled with a tracer 
```

I suppose we *could* turn off optimisations in such cases, but then it's not really clear what we're benchmarking.

This makes me think that either we should convert the `#[bench]` to `#[test]` (where they are meaningfully distinct tests) or drop them. Thoughts?

**Comment by vext01** [comment]
What about disabling optimisation for the `bench` profile using Cargo?

**Comment by vext01** [comment]
Closing, as this is for the old yk design.
