### ISSUE TITLE
Detecting untraced functions.

### ISSUE THREAD

**Issue by ptersilie** [ykjit/yk#249]
We currently annotate entire libraries with `#[do_not_trace]`, e.g. `core` and `alloc`. However, some of these functions (e.g. syscalls) aren't traced by the hardware tracer, which means we'll observe a call, but never see its return. This makes it difficult to detect the start/end of an untraced function, and thus currently requires storing that functions symbol name.

I'm not sure if there is a way to know which core library functions will be hardware traced, but if we can change the way we deal with libraries in the future, this hopefully will allow us to "optimise" the `do_not_trace` detection code.

**Comment by ltratt** [comment]
I *think* what you're saying is that in this code:

```rust
extern fn some_syscall() { ... }

fn g() {
  <do x>;
  some_syscall();
  <do y>;
}
```

if we're tracing `g` then we'll observe a call happening after `x` but we won't know what's being called (maybe?) or when it's returned if we don't track that we're currently in function `g`?

If I've got that right, I *think* this breaks with callbacks. Here's a contrived example:

```rust
extern fn some_syscall(f: &Fn ...) { f(); }

fn g() {
  <do x>;
  some_syscall(g);
  <do y>;
}
```

Now, AIUI, we'll stop tracing when we enter `some_syscall` then it calls `f` as a callback, and then we'll observe tracing of `g` again -- but it's not the same `g` on the callstack as earlier! [Obviously there's a lot more detail I'd need to put in here, and I don't even know if this idea of a syscall and callback can occur, but conceptually it looks like we might have a problem here.]

**Comment by ptersilie** [comment]
> if we're tracing `g` then we'll observe a call happening after `x` but we won't know what's being called (maybe?) or when it's returned if we don't track that we're currently in function `g`?

We know what's being called, but we won't know when we return from the system call, as we won't see it's return statement in the trace. In other words, we see the call to `system_call`, and the next thing we see is `<do y>`.

**Comment by ltratt** [comment]
> In other words, we see the call to system_call, and the next thing we see is <do y>.

Yes, we're talking about the same thing. I assume we track the fact that we *were* in `g` to make sure that when the trace does reappear, weird things don't happen? But I think my callback example above might break the name check.

**Comment by ptersilie** [comment]
I'm not sure. How does the callback work. Do we see:
```
g()
system_call()
g2()
return from g2()
```
or
```
g()
system_call()
g2()
return from g2()
return from g()
```

**Comment by ltratt** [comment]
There is no `g2` so you'll see:

```
<something in g>
system_call()
<something in g>
```

Is that second "something in g" the result of a callback or has `system_call` returned?

**Comment by ptersilie** [comment]
But at some point we will have to return from `g` and that's when we continue tracing again, which I think would be the correct thing to do.

**Comment by ltratt** [comment]
Yes, but how do you know which frame `something in g` refers to? It could be the original call frame or the callback call frame.

**Comment by ptersilie** [comment]
Wait, are we talking about tracing `g` or detecting when to continue tracing if `g` has been annotated with `do_not_trace`?

**Comment by ltratt** [comment]
AIUI the (or, at least, "a") challenge here is accurately reconstructing SIR from a trace.

**Comment by vext01** [comment]
When generating calls to an untraced function, could we call a wrapper which when lowered to SIR, looks like:
```
fn wrap_getuid() {
    enter_untraced(getuid); // special bytecode
    getuid();
    return_untraced(getuid); // special bytecode
}
```

Then the enter/return from untraced regions are explicit.

May come at a performance hit of course.

**Comment by ltratt** [comment]
> When generating calls to an untraced function, could we call a wrapper which when lowered to SIR

Yes, this is similar to @bjorn3's idea for the software tracer. I *think* that idea works there and here! We should try hard to break it, though, in case there's some edge case we haven't yet considered.

**Comment by ptersilie** [comment]
That is not going to help us with hardware tracing though, I think.

**Comment by ptersilie** [comment]
No I spoke to early, it should work for both.

**Comment by vext01** [comment]
I think it should work for both, at the cost of more functions (due to wrappers) and the indirection.

But correctness is probably more important than performance here. Hopefully the cost would only incurred in the interpreter. We can be careful to remove the wrappers when compiling the native code trace.

**Comment by ltratt** [comment]
> But correctness is probably more important than performance here.

No "probably" about it ;)

**Comment by vext01** [comment]
Closing, as this is for the old yk design.
