### ISSUE TITLE
Mapper is 64-bit centric. Should it be?

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#256]
As mentioned [here](https://github.com/softdevteam/yk/pull/226#pullrequestreview-585385749) the mapper uses a `u64` type for addresses, which is incorrect for 32-bit architectures.

 - ELF addresses are either 32 or 64-bit unsigned.
 - PT addresses are always 64-bit. No 32-bit x86 architecture has PT to my knowledge.
 - The maper is PT-centric.

**Comment by vext01** [comment]
This is, I believe, still true of the new LLVM-based yk design.

**Comment by ltratt** [comment]
We fixed this at some point in the past.
