### ISSUE TITLE
Tests are forced to use the unwind strategy, but the JIT assumes abort.

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#262]
See [here](https://github.com/softdevteam/yk/pull/226#discussion_r580376647)

**Comment by bjorn3** [comment]
Try `-Zpanic-abort-tests=yes`. This will enable `-Cpanic=abort` tests by running every test in an external process to prevent the whole test harness from crashing when any test panics.

**Comment by vext01** [comment]
Closing, as this is for the old yk design.
