### ISSUE TITLE
What is the role of `debug_assert!` in our code-base?

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#276]
In a regular Rust codebase, you'd typically use `debug_assert!` to detect bugs during development (but not in release builds).

Our system blurs the line between debug and release builds, as we rely on interpreter code being in debug mode for tracing to work. This means that we always pay the performance penalty of `debug_assert!`s.

Is this what we want? Probably not.

I wonder if we can redefine the `release` and `debug` profiles for the external workspace such that `release` mode is absent of debug assertions, but still unoptimised to allow tracing to work.

Good plan? Better ideas?

[A related issue is that, because we assume that we are built in debug mode, the trace compiler assumes that binary operations are checked -- it should probably make a decision based whether the external workspace has overflow checks enabled. Could be tricky to implement]

**Comment by ltratt** [comment]
I believe that `debug_assert` is controlled by the `debug_assertions` flag, which we should probably switch off when compiling the interpreter in "release" (ha!) mode.

Your last paragraph hints at a bigger issue which is worth thinking about: what rustc optimisations can we turn on and still have PT (and the SW tracer) still be OK? My intuition is "many maybe most rustc optimisations; few, if any, LLVM optimisations". At its extreme, *maybe* we *can* compile in `--release` from rustc's perspective, but not LLVM's?

**Comment by bjorn3** [comment]
For rustc the opt level barely matters. Almost all MIR optimizations either always run or only run when using the right `-Zmir-opt-level`.

**Comment by vext01** [comment]
> I believe that debug_assert is controlled by the debug_assertions flag, which we should probably switch off when compiling the interpreter in "release" (ha!) mode.

Agreed. I think we can just turn off optimisations in release mode, as debug_assertions is already off in that profile.

> What rustc optimisations can we turn on and still have PT (and the SW tracer) still be OK?
>
> For rustc the opt level barely matters. Almost all MIR optimizations either always run or only run when using the right -Zmir-opt-level.

If I understand, we can accept *all* MIR optimisations, since SIR is based on the final MIR. It's the optimisations that happen post-mir (e.g. LLVM) that could be problematic for us.

So perhaps we turn off optimisations, but send `-Zmir-opt-level=lightspeed-plz` (whatever the maximum is)?

**Comment by bjorn3** [comment]
`-Zmir-opt-level=3` is the maximum currently. Note that optimizations above `-Zmir-opt-level=1` (the default) have on several occasions proven to be unsound. Pretty much all known unsound optimizations have been moved behind `-Zunsound-mir-opts=yes` though.

**Comment by vext01** [comment]
I'll take a look at this shortly then. I expect we will find bugs when we turn up MIR optimisations.

**Comment by vext01** [comment]
Closing, as this is for the old yk design.
