### ISSUE TITLE
RawStopgapInterpreter has no ownership link to what it points to

### ISSUE THREAD

**Issue by ltratt** [ykjit/yk#304]
`RawStopgapInterpreter` is (effectively) `void *` which means we're executing code without any idea if the block of memory will be freed / moved. We need to rethink this so that there's some link between the two i.e. `RawStopgapInterpreter` (or some other intermediate struct) almost certainly needs to have sort of ref count or similar.

**Comment by vext01** [comment]
Closing, as this is for the old yk design.
