### ISSUE TITLE
UB observed in Terminator::Assert

### ISSUE THREAD

**Issue by ltratt** [ykjit/yk#306]
At the moment `yksg/src/lib.rs` has this chunk:

```rust
            Terminator::Assert {
                cond,
                expected,
                target_bb,
            } => {
                let b = self.read_int(cond) == 1;
                if b != *expected {
                    todo!() // FIXME raise error
                }
                self.frames.last_mut().unwrap().bbidx = *target_bb;
            }
```

If I change the `let b =` line to:

```rust
                let x = self.read_int(cond);
                assert!(x == 0 || x == 1);
                let b = x == 1;
```

tests fail with:

```
thread '<unnamed>' panicked at 'assertion failed: x == 0 || x == 1', yksg/src/lib.rs:387:17
```

That shows that we've hit UB at some point as the only valid value in memory for a bool is 0 or 1. [I hit this while trying to do https://github.com/softdevteam/yk/pull/299; that PR is on hold until we fix this]. I don't know when we hit the UB and it might be some time before this point (I guess `rr` might be a real help debugging this, but I might be wrong).

**Comment by ptersilie** [comment]
This is due to a liveness bug, which will be fixed with our upcoming new liveness analysis.

**Comment by vext01** [comment]
Closing, as this is for the old yk design.
