### ISSUE TITLE
Implement software tracing.

### ISSUE THREAD

**Issue by playXE** [ykjit/yk#318]
README says that it does not work but it wasn't updated for 2 months. I would like to try to use ykrustc and yorick for [starlight](https://github.com/starlight-js/starlight) (JS engine in Rust). I do not have access to Intel CPU so I have no other option except software tracing.

**Comment by ltratt** [comment]
It's on my list to see where we are with this and what needs to be done to get it up and running. @bjorn3 has done all the hard work so far!

**Comment by vext01** [comment]
We've since changed our design, so we currently have no software tracing support. We do however plan to implement it in the future.

**Comment by ltratt** [comment]
This is now in the works (the `swt` module).
