### ISSUE TITLE
Meta-hybrid JIT + yorick, is it possible in far future? 

### ISSUE THREAD

**Issue by playXE** [ykjit/yk#332]
There's [baccaml](https://github.com/prg-titech/baccaml) that does have meta-hybrid JIT Compiler. (research paper: https://dl.acm.org/doi/10.1145/3426422.3426977). To me it looks like generating method JIT using tracing JIT infrastructure is a nice feature to have. For example meta-hybrid JIT removes cons of tracing JIT that it does compile only one path. 

I'm not sure how this could be implemented when tracing LLVM IR. What I thought of is using fork() + COW on all the data so when tracing other part of conditional branch side effects does not break assumptions of previously created trace.

**Comment by vext01** [comment]
I'll close this for now, but please re-open if you want more discussion.
