### ISSUE TITLE
Refactor `createModule()`

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#385]
This function is responsible for assembling a trace by inlining the block that the hardware trace executed through.

The function is essentially nested loops:
```
for BB in Blocks {
  for Inst in BB {
    ...
  }
}
```

However, as we've added more and more JIT support, the function has become unmanageable.

The most icky aspect of this function is due to the fact that an LLVM `call` does not terminate a block. This means that when there is an inlined call, we have to stop copying instructions mid-block, start copying instructions from the callee's blocks, and when the callee returns, resume the original block **from where we broke off earlier**.

This has been implemented with a complicated spaghetti of `break`s and `continue`s, that ensure that each loop only runs proper when appropriate.

For example, a block like:
```
main:
  ...
  bb5:
    ...
    call f
    ...
```

Might give a trace like `<..., main:bb5, f:bb0, main:bb5, ...>`. Note that `main:bb5` appears twice because PT *does* consider a call to terminate a block. When building the trace, the second time we see `main:bb5` the loop attempts to `continue` enough times until we reach the instruction after call.

The problem is that this skipping logic is tangled up with the non-skipping logic and it's a real headache.

I suggest that:

 - We don't use nested loops to implement stepping over the trace. Instead we can have one loop and an "instruction pointer" which is a `(func, bb)` pair. The first thing the loop does is look up the block and instruction to inspect next. Then jumping to arbitrary places in a block is easy by modifying the instruction pointer, and we don't need a maze of `break`s and `return`s.

 - We use a separate function for containing the skipping logic so as to disentangle it from the main copying logic.

**Comment by ltratt** [comment]
We should assign this to someone... who?

**Comment by vext01** [comment]
I didn't assign anyone just yet, as now isn't the time for this refactoring.

**Comment by vext01** [comment]
(But I'm happy to work on this when the time comes)

**Comment by ltratt** [comment]
I think you should assign it to yourself then: it makes it less likely that this will be forgotten in the future.

**Comment by vext01** [comment]
#399 and #401 have addressed most of this.

Remaining tasks:

 - Review the fields of the `JITModBuilder` class. Should some of these be local scope in `createModule()`?
 - Group the incoming trace information into structs.
