### ISSUE TITLE
Constant expressions in call arguments are not handled correctly.

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#396]
For example a `GEPOperator` is mapped incorrectly. As I recall, the expression can reference something non-constant (e.g. a global), causing incorrect mappings.

The correct way to handle it would be to convert the expression to an instruction and map the new instruction.

**Comment by ptersilie** [comment]
I now wonder if the real reason for this had to do with the `VMap[x] == nullptr` bug. We should double check that.

**Comment by vext01** [comment]
Fixed by #406, right @ptersilie?

**Comment by ptersilie** [comment]
Yes.
