### ISSUE TITLE
Re-think the printing modes.

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#400]
During our sprint, I think we learned that:
 - The second column of "SBS" mode isn't very useful.
 - The line info of "SBS" mode is *very* useful.
 - Inlining thresholds annotated in SBS mode are somewhat useful.

I propose that we:
 - Remove SBS mode.
 - Make all print modes show debug line info (and inlining thresholds?).

This means:
 - Making the non-SBS modes print their modules line-by-line and porting the line info code over to them.
 - Finding out how to print the module-level bits like globals.

We should probably finish #392 first.

**Comment by ltratt** [comment]
I agree with this except:

> Inlining thresholds annotated in SBS mode are somewhat useful.

I'm not sure what this means.
