### ISSUE TITLE
There may be a better approach to the "BlockDisambiguate" pass in ykllvm.

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#435]
The `BlockDisambiguate` pass adds extra high-level basic blocks to make it explicit when a block re-executes itself at the high-level. This avoids ambiguities in the JIT runtime's mapping phase, where it may not be clear if a high-level block has been executed once or many times due to the way that machine blocks are generated.

The pass is sub-optimal:
 - It requires that some backend optimisations be (for now globally) disabled, to prevent the extra disambiguation blocks from being folded back in to their predecessor.
 - The addition of extra blocks may put pressure on the branch predictors and may worsen code coherency.

It would be better if the pass could run right at the end of the pipeline, mutating only machine blocks.

This is going to be tricky. I envisage that such an approach would look something like:

 - During instruction selection, when lowering the terminator of a high-level block, flag the machine instruction that re-executes the high level block. Add (`MIFlag::ReexecutesBlock` or similar).
 - When writing out the block map section, encode this flag against the entry for the parent basic block.
 - Find all places in the codegen pipeline where machine blocks can be folded into their predecessor and teach them not to if the flag is present.

Challenges:

 - Can a machine block contain more than a single branch? If so, how, in the block map,  do we identify which branches may re-execute the block, in a way that makes sense to the JIT runtime?
 -  Finding all of the places in the pipeline to teach about the new flag. It is at least the early tail duplication pass and  the (regular) tail duplication passes, and maybe others (branch folding pass and block placement pass?).

Failing this, a hybrid approach may be doable:
 - Mutate the high-level IR still.
 - But only disable backend optimisations for machine blocks that were generated from a high-level block that may branch directly back to itself.

**Comment by ltratt** [comment]
Enough has changed that this issue is no longer relevant.
