### ISSUE TITLE
Trace-stitiching should be implemented "in-jit-code"

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#442]
I'm about to raise a PR ([raised](https://github.com/ykjit/ykllvm/pull/12)) which implements trace stitching in the simplest fashion possible: the control point runs the JIT code (which currently runs only one loop iteration) repeatedly.

This works, but is sub-optimal, as there is function call overhead every time we exit and re-enter the JIT code. Ultimately the looping should be implemented in-jit-code.

(The reason I don't just implement proper stitching right off-the-bat is that it's not super-trivial)

**Comment by ptersilie** [comment]
Fixed in https://github.com/ykjit/yk/pull/736. I'm not sure why we thought it wasn't trivial. It could be that it wasn't when we started but our design has changed so much since then (e.g. shadow stack), that it is much easier now.
