### ISSUE TITLE
Re-add the ability to configure the JIT

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#449]
We used to be able to configure stuff like the hot counter via Rust methods on the `MT` struct.

Since moving to working at the LLVM-level, we've lost the ability to configure the tracer.

We probably need to add C functions that the interpreter author can call during initialisation. e.g. `yk_set_hot_threshold()`.

**Comment by ltratt** [comment]
This was fixed (mostly) by #472, so I'm closing.
