### ISSUE TITLE
Investigate using ORC instead of ExecutionEngine.

### ISSUE THREAD

**Issue by ptersilie** [ykjit/yk#450]
Apparently, `ExecutionEngine` is in maintenance mode, and development now happens in [ORC](https://llvm.org/docs/ORCv2.html). Using ORC should make things like finding the stackmap section much easier, so it could be worth investigating at some point.

**Comment by ptersilie** [comment]
Some more pointers:
- llvm/examples/HowToUseLLJIT (get started with LLJIT (an ORC-based replacement for MCJIT))
- llvm/examples/OrcV2Examples/LLJITWithObjectLinkingLayerPlugin (example of how to install your own passes for the JIT linker)

**Comment by ptersilie** [comment]
Using ORC is also an alternative to using the callback mechanism from `LLVMCreateSimpleMCJITMemoryManager`. We will have to use one or the other as our current solution isn't flexible enough. We are currently creating our own `RTyldMemoryManager` which `ExecutionEngine` takes ownership off, making it difficult to hold on to until the trace is no longer required.

**Comment by ltratt** [comment]
I think we can consider this one stale.
