### ISSUE TITLE
Drop semantics for `YkLocation`.

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#455]
Reviewing what we expose to C, there's a function (that I've recently overlooked) called `yk_location_drop()` which takes a location struct by value and calls Rust's drop on it.

I guess the intended workflow is:

 - user calls [`yk_location_new()`](https://github.com/ykjit/yk/blob/d06314efd341a37fd8a7aa011f998cfbcae79375/ykcapi/src/lib.rs#L32-L35) which returns from Rust (moving it?) a fresh stack allocated `Location` over the FFI.
   - By the way, C has a [mirror definition struct](https://github.com/ykjit/yk/blob/d06314efd341a37fd8a7aa011f998cfbcae79375/ykcapi/yk.h#L10-L25) which makes the location type non-opaque to C.
   - user can move this struct around, but probably shouldn't copy it.
 - user passes it into the control point many times.
 - user eventually drops it with [`yk_location_drop()`](https://github.com/ykjit/yk/blob/d06314efd341a37fd8a7aa011f998cfbcae79375/ykcapi/src/lib.rs#L37-L40) which calls the Rust [`Drop` impl](https://github.com/ykjit/yk/blob/d06314efd341a37fd8a7aa011f998cfbcae79375/ykrt/src/location.rs#L278-L289).

How do we feel about this? Is it still a good design?

It feels slightly fishy to me that the user could easily "accidentally" copy the (not opaque) struct obtained from `yk_location_new()` in C code. When they do this, they effectively make a new state machine for the same location and it might also encourage them to accidentally "double-drop" the Rust counter-part by calling `yk_location_drop()` on copies.

Maybe I'm worrying over nothing? The user shouldn't copy locations, only move them.

If we decide to keep this, the tests need to call the drop function (they currently don't).

**Comment by ltratt** [comment]
> When they do this, they effectively make a new state machine for the same location

Not really. The whole design of `Location`s allows them to be *moved*, so that you can use them with a compacting GC. In Rust, "move" and "copy" are distinct. C doesn't distinguish the two, so to enable moving, we have to allow copying. There's no sensible way around this.

> If we decide to keep this, the tests need to call the drop function (they currently don't).

Good point: yes, we should probably do this.

**Comment by vext01** [comment]
> Good point: yes, we should probably do this.

I'll do this now.
