### ISSUE TITLE
Tracing into the control point?

### ISSUE THREAD

**Issue by ltratt** [ykjit/yk#458]
I *think* we might be accidentally including parts of the internal control point mechanism in the trace. If I change `__yk_control_point` to:

```c
#[no_mangle]
pub extern "C" fn __ykrt_control_point(loc: *mut Location, ctrlp_vars: *mut c_void) {
    debug_assert!(!ctrlp_vars.is_null());
    if !loc.is_null() {
        eprintln!("before {:?}", unsafe {&*loc}.load(std::sync::atomic::Ordering::Relaxed));
        MT::transition_location(unsafe { &*loc }, ctrlp_vars);
        eprintln!("after {:?}", unsafe { &*loc}.load(std::sync::atomic::Ordering::Relaxed));
    }
}
```

then for `simple_interp_loop.c` I see this at the end:

```
before LocationInternalState { x: 4 }
counting
after LocationInternalState { x: 4 }
pc=1, mem=3
before LocationInternalState { x: 4 }
counting
after LocationInternalState { x: 4 }
pc=2, mem=3
before LocationInternalState { x: 4 }
counting
after LocationInternalState { x: 4 }
pc=3, mem=2
before LocationInternalState { x: 27176560 }
Compiling(Mutex { data: Some(CompiledTrace { entry: 0x7f7b80b00000 }) })
after LocationInternalState { x: 27176560 }
state 3
state 4
```

where (long story!) `state 3` == `Compiled` and `state 4` == `DontTrace`. There is only one place in the current code (in `mt.rs`) that sets `DontTrace` -- and that line of code definitely isn't being called. It looks very much like some bit of the code is "manually" incrementing a `Location` by 1 (hence the move from 3 to 4).

There's nothing obvious which does this increment, so I'm wondering if the most likely cause is that we're inlining parts of the control point into the trace. For example, when we trace multiple opcodes in ykcbf, I wonder if we include the control points for each of the opcodes *as we're tracing it and that also ends up in the compiled machine code*?

Help is very much appreciated, as I am not sure where to start hunting this one down!

**Comment by ltratt** [comment]
I have pushed my code which shows this problem to https://github.com/ltratt/yk/tree/location_state. Another possibility is that this is something to do with us not having proper guard failure yet.

**Comment by vext01** [comment]
OK, I've reproduced the issue and I think I see the problem.

The `4` you see is the Rust side of the code reporting that the trace is in the `Compiled` state (not that it is in `DoNotTrace` state). In [`location::state()`](https://github.com/ltratt/yk/blob/02bb85c89f364889b665ed89af77b6ad5522c434/ykrt/src/location.rs#L153) we have:

```
HotLocation::Compiled(_) => LocationState::Compiled,
```

Where this is defined (on the Rust side) as:

```
Compiled = 4,
```

I suspect that the confusion branches from the C-side constants not being in sync with the rust side?

```
pub enum LocationState {
    /// The precise state of this [Location] is currently unknown (e.g. because it is locked
    /// waiting for another thread to do something).
    Unknown = 0,
    /// This [Location] is not yet hot.
    Counting = 1,
    /// This [Location] has caused a trace to start at some past point in time. It is impossible to
    /// know if that trace is ongoing or has been aborted.
    MaybeTracing = 2,
    /// This [Location] has successfully completed a trace, and that trace is currently being
    /// compiled.
    Compiling = 3,
    /// This [Location] has a compiled trace.
    Compiled = 4,
    /// This [Location] has been marked as "do not trace". This is not necessarily permanent.
    DontTrace = 5
}
```

vs:

```
enum YkLocationState {
  YK_LOCATION_STATE_COUNTING = 0,
  YK_LOCATION_STATE_TRACING = 1,
  YK_LOCATION_STATE_COMPILING = 2,
  YK_LOCATION_STATE_COMPILED = 3,
  YK_LOCATION_STATE_DONT_TRACE = 4,
};
```

Presumably these two enums should be in sync? Do we want them to be a one-to-one mapping, or do we want to expose only a subset of them to C? For example, is `MaybeTracing` something that should be in the C enum?

**Comment by ltratt** [comment]
If you sync them does the problem go away?

**Comment by ltratt** [comment]
[Sorry, I don't remember why they aren't synced.]

**Comment by vext01** [comment]
The test gets as far as a guard failure, i.e. it no longer waits indefinitely.

After lunch I will review the test to see if it's exactly what we want.

**Comment by vext01** [comment]
One thing we need thing about is that by adding:

```
if (st != YK_LOCATION_STATE_MAYBE_TRACING && st != YK_LOCATION_STATE_COMPILING) {
  yk_location_wait(loc, YK_LOCATION_STATE_COMPILED);
}
```

we are going to end up tracing that logic too, which probably isn't what we want.

**Comment by ltratt** [comment]
> we are going to end up tracing that logic too, which probably isn't what we want.

Temporarily we can probably live with it. At some point soon-ish we'll need an explicit `do_not_trace` annotation for functions to avoid things like this. It might even make sense to have a debug-only control point that serialises computation by including the `if` (and loop) above.

**Comment by vext01** [comment]
> Temporarily we can probably live with it

I'm not sure I understand the intention of the `st != YK_LOCATION_STATE_MAYBE_TRACING && st != YK_LOCATION_STATE_COMPILING` condition, but first, let's take a step back, as I'm confused about something more fundamental.

As I understand, we are trying to find a way to write tests that can deal with non-determinism in a multi-threaded environment, but I'm not sure how your branch ties in with that.

We already have a way to "wait" for certain events with the jit-state printing and lang_tester. What we don't have is a way to match the interleaved output of many threads all running the interpreter loop at once (although we could easily fix this by adding a thread id to each jit-state print).

I guess what I'm asking is: what does this solve, and how is this better than using conditionally compiled print statements like we do currently? The jit-state prints add no extra code to the interpreter loop, cause no spurious guards to be inserted, and require no annotations.

**Comment by ltratt** [comment]
> We already have a way to "wait" for certain events with the jit-state printing and lang_tester

No, those don't *wait*: they just print out *when* something has happened. That doesn't work in the parallel-computation context because compiling can take arbitrarily long. For example if I have this loop:

```rust
for _ in 0..1000000 {
  ...
}
```

it might get traced on the first iteration but we have no guarantee that it will be compiled into machine code before the loop terminates. Any test we write based on that assumption will, at best, be flaky (and possibly incorrect).

What my commit gives the user is a way of saying "keep running this thing until a particular JIT event(s) has occurred". If you wan to wait until a loop is compiled, for example, you can (there's no guarantee *when* this will happen, so there's still some flakiness left, but there's nothing we can do about that).

**Comment by vext01** [comment]
Ah ha! I think I see what you are saying.

In my own words:

> for _ in 0..1000000 {

There's no telling what the upper bound for this loop would need to be to ensure that compilation has completed on any arbitrarily slow / arbitrarily loaded CPU. Right?

Assuming that's the case, I agree that this waiting tactic is a good one. It also occurs to me that we must ensure that all threads wait (and I think that is what you are doing here too).

Can we find a way to do it that requires no additional code inside the interpreter loop? That way we don't have to retroactively remove/ignore things from the trace we've collected (Lukas and I have tried hard to not clutter up the trace with meta-jit-related stuff, as it often causes headaches which require ad-hoc fixes later down the line).

For example, we could have an environment variable which blocks (inside of the control point) if a location is being compiled.

> debug-only control point

I guess that is what you were aiming at with this. I'm OK with that too, but I think we should do it now, rather than later. Sounds good?

**Comment by vext01** [comment]
Having fiddled around a bit, it seems that I had overlooked one aspect: in the long run, compilation may succeed or fail. This is probably why you exposed all of the different states to C, so that you could arbitrarily wait for any given state, depending upon the intention of the test.

I'm going to think some more. There must be a way to do this without junking up the interpreter loop.

**Comment by ltratt** [comment]
> in the long run, compilation may succeed or fail

That is true, although it's more that tracing may succeed or fail (compilation of a trace failing probably indicates a deeper problem).

> There must be a way to do this without junking up the interpreter loop.

The only other way is to have something like `synchronous_compile_control_point` that hides this sort of thing behind an opaque function.

**Comment by vext01** [comment]
> compilation of a trace failing probably indicates a deeper problem

You are right.
 
Maybe it's going to be OK after all. Let me see what I can come up with.
