### ISSUE TITLE
Compilation thread should transition a location to Compiled the moment compilation is complete.

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#462]
Currently, when the compilation thread finishes compiling a trace, it simply stores the trace inside the existing `HotLocation::Compiling(...)`, changing the inner `Option` from `None` to `Some`. Then later an interpreter thread (when inside the control point) notices that the location is `HotLocation::Compiling(Some(ct))` and flips it to `HotLocation::Compiled(ct)`.

It would make more sense if the compilation thread itself flipped the `HotLocation` to `Compiled` the moment compilation is completed.

Also the wait logic in `Location::block_if_compiling()` could then simply spin until the `HotLocation` is no longer `HotLocation::Compiling` any more, and it can do this without any knowledge of how compiled traces are stored, or of the mutex that guards them.

**Comment by ltratt** [comment]
I'll take this one on (it's not critical).
