### ISSUE TITLE
Refactor ykcapi crate.

### ISSUE THREAD

**Issue by ltratt** [ykjit/yk#510]
At least as originally envisaged, and as currently named, `ykcapi` is meant to be "the API that C programmers can use to yk". However, we've also bunged in internal-yk details in there: `yk_stopgap` and ` __llvm_deoptimize`. Ideally these functions would live in `ykrt`, but maybe that's not possible for some compilation reason? If not, maybe we could/should create another crate with these oddballs in, so that normal users don't get confused when they look at `ykcapi`?

**Comment by vext01** [comment]
It's because of the way Cargo works: only one crate in a workspace can be a cdylib or weird things happen at the linkage stage (usually symbol clashes).

So `ykcapi` is the crate for "exposing C stuff".

OK for me to close this?

**Comment by ltratt** [comment]
Let's not close this yet. A partial fix might be to do something like separate out "files that a C user of yk will want to look at" vs. "files that are internal to yk"?

**Comment by vext01** [comment]
That would work, as long as ykcapi is the only crate that exports C symbols via a dynamic library.

**Comment by ltratt** [comment]
We haven't *fully* fixed this, but the general reorg of code around yk has started to chip away enough at this that this issue isn't really useful anymore.
