### ISSUE TITLE
Deal with nested loops properly

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#519]
For the situation where there are nested loops in the interpreter. The inner loop will be JIT compiled first, then later the outer loop will eventually be compiled too. It would be best if the outer loop called the existing trace for the inner loop, rather than duplicating JITted code for the inner loop.

**Comment by ltratt** [comment]
> The inner loop will be JIT compiled first, then later the outer loop will eventually be compiled too.

Not necessarily: either loop can be compiled in either order.

We should probably check in more detail what RPython does for nested loops, as I don't remember the whole story. For example, one thing we *could* do is say that if you have loops where the outer loop becomes hot before the inner loop, it's fine to unroll in the inner loop (this would be the current behaviour).

**Comment by vext01** [comment]
> Not necessarily: either loop can be compiled in either order.

Due to non-atomicity of hot counts?

**Comment by ltratt** [comment]
This is a totally normal property of loops: nothing to do with JITs. [One random example of an interesting case is if the inner loop is behind an `if`.]

**Comment by vext01** [comment]
Good point! I have no idea why I didn't consider this case!

**Comment by ltratt** [comment]
Closing this because it's not very specific about which of the possible problems with loops it might be talking about.
