### ISSUE TITLE
Event-based testing.

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#522]
Over the last few days, we've identified a need for what I'm going to call "event-based" testing.

In this model, we run a test until a certain event of interest (non-deterministically) occurs. For example, we might run an infinite interpreter loop until a at least one location executes a trace.

I imagine this will require either the signature of the control point to change (I'd like to avoid that) or perhaps the interpreter loop would be something like:

```
yk_test_until(<some specification>)

while (yk_more_testing()) {
  yk_mt_control_point(...);
  ...
}
```

Feel free to propose other ideas.

**Comment by ltratt** [comment]
Solved by `YKD_SERIALISE_COMPILATION`.
