### ISSUE TITLE
In multi-threaded testing, threads can dump interleaving modules

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#523]
When using `YKD_PRINT_IR` in testing, if two threads compile at the same time, they might print their modules at the same time, in which case, they tend to interleave.

This makes lang_testing hard.

We might consider using a lock to ensure that only one thread dumps its module at a time. This comes at the cost of sequentialising the threads a bit more that is strictly necessary.

**Comment by ltratt** [comment]
We now have `YKD_SERIALISE_COMPILATION` which solves this issue.
