### ISSUE TITLE
Properly handle failed trace compilation.

### ISSUE THREAD

**Issue by ptersilie** [ykjit/yk#612]
Currently, when a trace fails to compile, we just ignore it and move on. Soon, we want to handle this better, and depending on why the compilation failed, never try this location again, or try it again later.

**Comment by ltratt** [comment]
We haven't fully fixed this, but between https://github.com/ykjit/yk/pull/806 and https://github.com/ykjit/yk/pull/811 I would say we are now sufficiently close that this issue is no longer relevant.
