### ISSUE TITLE
Use cached copy for llvmbridge::Module.

### ISSUE THREAD

**Issue by ptersilie** [ykjit/yk#617]
The module in https://github.com/ykjit/yk/blob/master/ykfr/src/llvmbridge.rs#L14 loads a new module in every time we deoptimise, which is very slow. We already have cached loading logic in `ykllvmwrap`, which, once exposed to Rust, could be reused here.

**Comment by ltratt** [comment]
We've partially done this (in https://github.com/ykjit/yk/pull/801), and deopting is something we're going to look at in more depth soon anyway, so closing this.
