### ISSUE TITLE
New PT packet type?

### ISSUE THREAD

**Issue by ltratt** [ykjit/yk#623]
From #622:

> "In state Normal, failed to parse packet from bytes: 00000010, 11110011, 00000000, 00000000, 00000000, 00000000, 00000000, 00000000, ..."

**Comment by vext01** [comment]
@ltratt do you think it's important to differentiate the two cases in the error propagated by our decoder?

**Comment by ltratt** [comment]
I'm not sure I understand the difference between the two. Can you explain it to me like I'm an idiot so I can try and understand?

**Comment by vext01** [comment]
> Should we lump the former in with that?

The PR you just borsed uses the same error variant for both.

**Comment by vext01** [comment]
OK.

I wonder what github will do when the `Fixed #XX` in the commit message finds an already closed issue :P
