### ISSUE TITLE
JIT blocking signals?

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#658]
I notice that if you press CTRL+C while running a jitted interpreter, it can take some time (many seconds) for the process to be killed.

**Comment by ltratt** [comment]
This might be because `SIGINT` doesn't take full effect until all threads have finished? To be honest, I'm not very sure what signals and multiple threads are supposed to do -- I think it's recommended not to handle signals on anything except the main thread, but my memory might be wrong there.

**Comment by ltratt** [comment]
I think the observation (killing the interpreter can take a long time as yk threads might be doing work) is correct, but it's not clear there is anything much we can, or should, do about that. On that basis, closing.
