### ISSUE TITLE
gdb_c_test tool will fail to run if you first haven't built the `tests` crate.

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#666]
`cargo run --bin gdb_c_test` will fail if you don't first run `cargo build --tests`.

Something is wrong with the deps?

**Comment by ltratt** [comment]
I'm not sure what "fail to run" means (fails to build or ... ?), but with a fresh checkout:

```
$ cargo run --bin gdb_c_test
error: the following required arguments were not provided:
  <TEST_FILE>

Usage: gdb_c_test <TEST_FILE>
```

I don't know what `gdb_c_test` does or how to run it, so I can't tell if it's fixed or not.

**Comment by vext01** [comment]
I think this issue is bogus.

The tool is in the `tests` crate, so yah, if you don't build the crate, you don't get the tool.

```
./tests/src/bin/gdb_c_test.rs
```

(this tool could do with being documented, yes)
