### ISSUE TITLE
Passing arbitrary arguments to cmake (when building LLVM).

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#675]
With our new build system, I've lost the ability efficiently to build LLVM with distcc, since it requires me to passing a custom `-j` value to `cmake --build`. This is needed because otherwise cmake/ninja will try to spawn a number of jobs suitable for the local system, not for the distributed systems.

The `cmake` crate is a bit annoying in that it categories each of the different kinds of argument you could pass to `cmake`, for example:

 - `-DKEY=VAL` means calling `ykllvm.define("KEY", "VAL");`
 - whereas passing `-j42` means calling `ykllvm.build_arg("-j42")`

(There are others that users may want to customise, like if they want to force using Makefiles, `-G"Unix Makefiles"` becomes `ykllvm.generator("Unix Makefiles")`)

This is why currently `YKB_YKLLVM_BUILD_ARGS` assumes that it only contains `-D` arguments, so it can always call `.define()`.

So, there are two ways forward:
 - Make `YKB_YKLLVM_BUILD_ARGS` general and parse it, dispatching to the right cmake methods.
 - Make `YKB_YKLLVM_BUILD_ARGS` for only passing `.build_args()`, and have a `YKB_YKLLVM_DEFINES` (or similar) for calling `.defines()`.

I'm leaning towards the latter, but I question if we would also rename:

 - `YKB_YKLLVM_BUILD_ARGS` -> `YKB_YKLLVM_CMAKE_BUILD_ARGS`
 - `YKB_YKLLVM_DEFINES` -> `YKB_YKLLVM_CMAKE_DEFINES`

**Comment by vext01** [comment]
I don't mind doing the work, but note that this requires input from others.

Are you all OK with the latter of the options in the issue description?

**Comment by ltratt** [comment]
I don't feel too strongly about this (and I think this is an issue that needs to be solved by a distcc user) but I would prefer to minimise the number of env vars, so I'd be inclined to stick with a single var (e.g. `YKB_YKLLVM_BUILD_ARGS` -- though I now realise that is both `YKB` and `BUILD` so should it be just `YKB_YKLLVM_ARGS`?). Since we're not worried about trying to solve the fully general shell argument parsing problem, a simple/custom parser of this var to deal with `cmake`s should be fine.

**Comment by vext01** [comment]
OK, leave it with me.

**Comment by jacob-hughes** [comment]
Yes this is unfortunate. It would be much easier if you could just pass all the different kinds of `cmake` args directly. I think I agree with @ltratt that it would be nicer if we reduced the number of env vars, but I think at least two are needed to differentiate between the configure and build phases?
