### ISSUE TITLE
Build system invokes `llvm-config` from $PATH

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#679]
Having studied the build system, I've noticed that [`llvm-config` is being called from the $PATH](https://github.com/ykjit/yk/blob/c83b21c54301baf67c15bcbc5055620d79cb87b2/ykbuild/src/lib.rs#L12).

In the CI the path is updated to [point to a manually built llvm](https://github.com/ykjit/yk/blob/master/.buildbot.sh#L59).

I think this means that the build is going to always use parts of this ykllvm, instead of the intended one. Possibly linking multiple llvms(?).

I *think* the build system should call `llvm-config` by absolute path and that the CI script should not update PATH(?).

**Comment by ltratt** [comment]
Yes, I noticed and "fixed this" in https://github.com/ykjit/yk/pull/677 -- but that PR, overall, cannot be completed I think. I'm going to close this issue because in #677 I suggest alternative means ahead that would also involve implicitly fixing this issue.
