### ISSUE TITLE
Should yk-config be for C API users only?

### ISSUE THREAD

**Issue by ltratt** [ykjit/yk#712]
At the moment, `yk-config` is tucked away inside `ykcapi` implying that only users of the C API need to know about it. That is possibly a valid thing to do (though having the directory be called `scripts` I'm not keen on, but that's a side issue), but should `yk-config` be restricted to C API users? For example, most yk users will probably need to know what linker flags to use. Now, admittedly, we could say that "for each API (e.g. C, Rust, etc etc) we provide some sort of `yk-config`ish thing appropriate for that API" or we could say "there is a global `yk-config` and you can query it with questions appropriate for your API". One advantage of the latter is that it might play better with systems that have a mix of languages (e.g. C and Rust). Any thoughts?

**Comment by vext01** [comment]
`yk-config` was based on pkg-config-style scripts like `llvm-config`. These are typically for C or C++.

Would a language like rust need such a script? You'd just add a crate to your deps, wouldn't you?

**Comment by ltratt** [comment]
Maybe it should be `ykcapi-config`? That would also allow us to install it globally (e.g. in `/usr/local/bin/`) without worrying about it stomping on config exes for other yk APIS.

Whatever we name the config program, I would also like to move it out of `scripts`. Either `ykcapi/bin` or just at the top-level of `ykcapi` would be OK with me: any thoughts?
