### ISSUE TITLE
Look at the vestiges of the stopgap interpreter

### ISSUE THREAD

**Issue by ltratt** [ykjit/yk#713]
We have long since removed the stopgap interpreter -- but it lives on in comments and, particularly, in many tests with `stopgap` in the name, most of which are `ignore`d. We should remove all of the tests which don't make sense without a stopgap interpreter and fix all comments.

[I used `rg -l "stop.*gap"` to find all the places that reference stopgapping. Ideally that should soon return no results at all.]

**Comment by ltratt** [comment]
This was mostly fixed by https://github.com/ykjit/yk/pull/716. I still see 3 files with "stopgap" in them:

```
$ rg -l "stop.*gap"
tests/c/bfbug.c
tests/c/simple_interp_loop1.c
tests/c/direct_recursion.c
```

Of those, `bfbug.c` says:

> // FIXME: This only returns an integer due to a shortcoming of the stopgap interpreter: https://github.com/ykjit/yk/issues/537

which is out of date.

`simple_interp_loop1.c` has `//     jit-state: stopgap` but I think that's just because the test needs updating when the shadow stack supports dynamic resizing? [see https://github.com/ykjit/yk/issues/715]

`direct_recursion.c` looks out of date and I think can be killed.

I'll raise a PR to deal with `bfbug.c` and `direct_recursion.c`. @ptersilie what about simple_interp_loop1.c ?

**Comment by ltratt** [comment]
Correction: `direct_recursion.c` is actually a useful test (I misread it at first because I'm an idiot). https://github.com/ykjit/yk/pull/718 reenables it.

**Comment by ptersilie** [comment]
As you point out correctly, `simple_interp_loop1.c` is one of a few tests that allocates stuff on the stack dynamically, which our shadow stack approach currently deal with. I think we should keep it until we've fixed that, though I don't have an ETA on that.

**Comment by ltratt** [comment]
Closing this because I think the "stopgap" aspect of `simple_interp_loop1.c` is no longer very relevant to the bigger "shadow stack" question(s).
