### ISSUE TITLE
Side traces need info about last executed trace at control point

### ISSUE THREAD

**Issue by ptersilie** [ykjit/yk#724]
In order to implement side traces we need a way to check whether we have just guard failed a compiled trace when encountering the control point. I briefly discussed this with @ltratt who suggested storing the memory address of the executed trace somewhere, so we can then check this against the address stored in the location at the control point.

In the meantime I will start working on starting tracing when a guard fails (probably immediately at first, but will require a hotness counter fairly quickly too). We then also need to work out where to store the compiled side traces.

**Comment by ltratt** [comment]
Fixed long ago.
