### ISSUE TITLE
JIT stats facility.

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#798]
It would be useful to have a way to understand where the runtime of an interpreter is spent.

Ideally we'd like to know how much time was spent on:
 - interpreting
 - trace collection
 - trace compilation
 - deopt

(We should think about if we want/can report these on a per-trace basis -- obviously that makes no sense for interpretation)

It may also be useful to know:
 - How long the trace is, measured in IR instructions.
 - How big the compiled (e.g. x86_64) code is, in bytes.
 - How many times the trace was executed.
 - Which guards failed, and how many times.

For a first stab at this, we could just report how long we spent in trace compilation and the size of the trace? That's the bottleneck at the moment.

**Comment by ltratt** [comment]
Fixed in https://github.com/ykjit/yk/pull/799.
