### ISSUE TITLE
Unchecked dlsym

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#835]
This call to `dlsym` is unchecked. If the symbol doesn't exist, dlsym returns null and we erroneously use it.

https://github.com/ykjit/yk/blob/4a955668d5a6647c5de8f043314983f057a5039e/ykrt/src/compile/jitc_llvm.rs#L151

It's been on my list for a while to write a wrapper around `dlsym` and funnel all uses of dlsym through it.

When hacking the new prototype code generator I actually wrote a wrapper:
https://github.com/vext01/yk_pv/commit/34d9dfea42c5c2a393da9e1a0f3833f729e26269#diff-aa389a21efb030fbbaf6bba425c697d7076980ec84b58822881b2acc78d3778cR148

We could use/amend this.

Maybe @ltratt would like to have a stab at this?

**Comment by ltratt** [comment]
I think we need to rethink this stuff at a higher level, but I currently lack any meaningful understanding of how to improve it.

**Comment by vext01** [comment]
Just check if it's null and return `None` if so. Otherwise we seg.

**Comment by ltratt** [comment]
This is an issue with a backend we intend retiring. Closing.
