### ISSUE TITLE
libykcapi.so invalid ELF error

### ISSUE THREAD

**Issue by Pavel-Durov** [ykjit/yk#845]
Related YkLua Issue: https://github.com/ykjit/yklua/issues/58

When running resiliency tests (`try_repeat 1000`) sometimes we get this error:
```shell
../src/lua: error while loading shared libraries: /yk/bin/../target/debug/deps/libykcapi.so: invalid ELF
```

It's hard to reproduce as it is non-deterministic and happens very rarely.

**Comment by vext01** [comment]
Can you show me the `try_repeat` invocation?

**Comment by Pavel-Durov** [comment]
Failed (731 run):
```shell
YKD_SERIALISE_COMPILATION=1 try_repeat -v 1000 ../src/lua -e"_U=true" coroutine.lua
../src/lua: error while loading shared libraries: /home/pd/yk-fork/bin/../target/debug/deps/libykcapi.so: invalid ELF 
```

**Comment by vext01** [comment]
So you don't rebuild yk inbetween runs even.

I agree with Laurie that this appears to be another process (LSP?) building yk at the same time.

Either that or a loader bug (seems unlikely).

**Comment by Pavel-Durov** [comment]
I just re-ran `try_repeat -v 1000` successfully
Maybe was re-compiling yk in the background, not sure 😶
