### ISSUE TITLE
callsite_off < return_off

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#908]
Found with `try_repeat`:

```
>> |thread '<unnamed>' panicked at hwtracer/src/llvm_blockmap.rs:161:21:                                            
   |assertion failed: callsite_off < return_off                                                                     
```

when running  `lang_tests::reentrant.c`

**Comment by ltratt** [comment]
Out of curiosity, do you have a sense of how often it fails? [`try_repeat -v` can be quite interesting here.]

**Comment by vext01** [comment]
I've gotten it twice in a row on run #1 on this particular machine.

**Comment by vext01** [comment]
And a third time.

So this is deterministic on that machine.
