### ISSUE TITLE
Is `bb: usize::MAX` a valid value?

### ISSUE THREAD

**Issue by ltratt** [ykjit/yk#960]
A question for @vext01. In `trace/mod.rs` we have:

```rust
pub enum TracedAOTBlock {
    /// A sucessfully mapped block.
    Mapped {
        /// The name of the function containing the block.
        ///
        /// PERF: Use a string pool to avoid duplicated function names in traces.
        func_name: CString,
        /// The index of the block within the function.
        ///
        /// The special value `usize::MAX` indicates unmappable code.
        bb: usize,
    },
    /// One or more machine blocks that could not be mapped.
    ///
    /// This usually means that the blocks were compiled outside of ykllvm.
    Unmappable,
}
```

AFAICS `bb = usize::MAX` is pointless since it's equivalent to TracedAOTBlock::Unmappable? Indeed, if I add an assert to `TracedAOTBlock::new_mapped`:

```rust
impl TracedAOTBlock {
    pub fn new_mapped(func_name: CString, bb: usize) -> Self {
        assert_ne!(bb, usize::MAX);
        Self::Mapped { func_name, bb }
    }
```

all our tests pass, so i guess the "special value" comment reflects some past state that's no longer relevant?

**Comment by vext01** [comment]
This didn't used to be an enum, and an unmappable block was expressed by the special value. I believe that you are right that `usize::MAX` is now irrelevant.  I've done a quick grep to confirm this.

I tried to find the commit where this became an enum, but since the file was moved and the type renamed, it's hard to find, sorry.

**Comment by ltratt** [comment]
I also couldn't find anything. I'll raise a PR to remove the comment, but I'll leave the `assert` in --- just in case!

**Comment by vext01** [comment]
@ltratt Was this one fixed?

**Comment by ltratt** [comment]
I left an `assert` in to catch any lagging uses of this. That's been there long enough that I think we can get rid of it. About to raise a PR...
